[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bincode = "1.3"  
async-std = "1.10"
serde = { version = "1.0", features = ["derive"] }